### ISSUE TITLE
Adding new catalog, do nothing after clicked ok

### ISSUE THREAD

**Issue by luipir** [boundlessgeo/qgis-geoserver-plugin#5]
log says:
Traceback (most recent call last):
  File "/home/ginetto/.qgis2/python/plugins/geoserverexplorer/gui/dialogs/catalogdialog.py", line 210, in okPressed
    while newname in self.explorer.catalogs().keys():
AttributeError: 'dict' object has no attribute 'catalogs'

**Comment by luipir** [comment]
could be a regression... it works in the OpenGeo suire 4.7 plugin version
