### ISSUE TITLE
Python setuptools no longer ships with easy_install

### ISSUE THREAD

**Issue by mikefedak** [boundlessgeo/qgis-geoserver-plugin#97]
https://github.com/boundlessgeo/qgis-geoserver-plugin/blob/6a5e68d994057349dffa82b95cfdeed651994153/pavement.py#L91

In newer versions of pip (>9.0.1) that ship with Ubuntu 18.04 easy_install is no longer available. If you change the line to `pip install -d` the setup and install proceeds (provided you have sphinx installed).

**Comment by mikefedak** [comment]
The install finishes successfully but qgiscommons is not installed, only downloaded. After manually building qgiscommons, and copying the build to the extlibs directory, the plugin loaded in qgis 3.2.2 without issue.

**Comment by mikefedak** [comment]
Likely related to the hacky installation. I receive the following error regardless of which geoserver I connect to:

n error has occurred while executing Python code: 

TypeError: QgsMessageBar.pushMessage(): arguments did not match any overloaded call:   overload 1: argument 2 has unexpected type 'bytes'   overload 2: argument 2 has unexpected type 'bytes'   overload 3: argument 2 has unexpected type 'bytes' 
Traceback (most recent call last):
  File "/home/mike/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 325, in addGeoServerCatalog
    geoserverItem.populate()
  File "/home/mike/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 528, in populate
    self._populate()
  File "/home/mike/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 539, in _populate
    self.workspacesItem.populate()
  File "/home/mike/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 417, in populate
    workspaces = cat.get_workspaces()
  File "/home/mike/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoserverexplorer/extlibs/geoserver/catalog.py", line 1030, in get_workspaces
    data = self.get_xml("{}/workspaces.xml".format(self.service_url))
  File "/home/mike/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoserverexplorer/extlibs/geoserver/catalog.py", line 237, in get_xml
    raise FailedRequestError(resp.content)
geoserver.catalog.FailedRequestError: b'
HTTP Status 401 - Bad credentials

type Status report
message Bad credentials
description This request requires HTTP authentication (Bad credentials).

Apache Tomcat/6.0.18
'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mike/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 289, in 
    createCatalogAction.triggered.connect(lambda: self.addGeoServerCatalog(explorer))
  File "/home/mike/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 328, in addGeoServerCatalog
    explorer.setWarning(e.args[0])
  File "/home/mike/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoserverexplorer/gui/explorer.py", line 158, in setWarning
    duration = 10)
TypeError: QgsMessageBar.pushMessage(): arguments did not match any overloaded call:
  overload 1: argument 2 has unexpected type 'bytes'
  overload 2: argument 2 has unexpected type 'bytes'
  overload 3: argument 2 has unexpected type 'bytes'


Python version: 3.6.5 (default, Apr  1 2018, 05:46:30) [GCC 7.3.0] 
QGIS version: 3.2.2-Bonn Bonn, 2684216 

Python Path:
/usr/share/qgis/python
/home/mike/.local/share/QGIS/QGIS3/profiles/default/python
/home/mike/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/mike/.local/share/QGIS/QGIS3/profiles/default/python
/home/mike/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoserverexplorer/extlibs

**Comment by SrNetoChan** [comment]
Can you try setting up with `paver setup -c` to configure and download all the dependencies?
And the `paver install` to create the symlink to QGIS 3 default profile folder.

That has been working well on my 18.04 machine.

**Comment by volaya** [comment]
Thereae to things happening in that error when trying to add a catalog:

First, the credentials seem to be wrong, so the server complains and returns a 401 error. The plugin is not handling that correctly, and that causes the exception you are seeing. I just fixed it, so you should be able to connect now (with the correct credentials :-) ) or get a better message in case there is an auth error

**Comment by mikefedak** [comment]
> Can you try setting up with `paver setup -c` to configure and download all the dependencies?
> And the `paver install` to create the symlink to QGIS 3 default profile folder.
> 
> That has been working well on my 18.04 machine.

Thank you, this worked for simplifying the installation.

**Comment by mikefedak** [comment]
> Thereae to things happening in that error when trying to add a catalog:
> 
> First, the credentials seem to be wrong, so the server complains and returns a 401 error. The plugin is not handling that correctly, and that causes the exception you are seeing. I just fixed it, so you should be able to connect now (with the correct credentials :-) ) or get a better message in case there is an auth error

This works as long as you have a username/password. Just to clarify, is it a necessity to have a username and password to use this plugin? If you do not specify credentials then the following error happens:

```
AttributeError: 'NoneType' object has no attribute 'authid' 
Traceback (most recent call last):
  File "/home/mike/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 605, in 
    editAction.triggered.connect(lambda: self.editCatalog(explorer))
  File "/home/mike/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 619, in editCatalog
    self.catalog.authid = dlg.authid
AttributeError: 'NoneType' object has no attribute 'authid'


Python version: 3.6.5 (default, Apr  1 2018, 05:46:30) [GCC 7.3.0] 
QGIS version: 3.2.2-Bonn Bonn, 2684216 

Python Path:
/usr/share/qgis/python
/home/mike/.local/share/QGIS/QGIS3/profiles/default/python
/home/mike/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/mike/.local/share/QGIS/QGIS3/profiles/default/python
/home/mike/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoserverexplorer/extlibs
/home/mike/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoserverexplorer/extlibs/python_dateutil-2.7.3-py2.7.egg
/home/mike/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoserverexplorer/extlibs/six-1.11.0-py2.7.egg
/home/mike/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geoserverexplorer/extlibs/requests-2.5.0-py2.7.egg
```

**Comment by volaya** [comment]
As far as I see, the eror is not when adding a catalog for the first time, but when editing it. I fied it, so now it will correctly handle the case of blank user or blank password.

However, I am not sure geoserver will allow you to access with credentials... Can it be configured like that?

Thanks for your help!
